---
title: "R Notebook"
output: html_notebook
---

### Install package renv for R version control

```{r}
install.packages("packrat")
```
### Innitiate project local environment

```{r}
library(packrat)
```

```{r}
sessionInfo()
```

```{r}
packrat::init()
```

```{r}
library(devtools)
```




### Install the right versions of the packages
```{r}
install.packages("tidyr", version = "1.1.2", repos = "http://cran.us.r-project.org")
```

```{r}
install.packages("tibble", version = "3.0.4", repos = "http://cran.us.r-project.org")
```
```{r}
install.packages("dplyr", version = "1.0.2", repos = "http://cran.us.r-project.org")
```
```{r}
install.packages("rlang", version = "0.4.8", repos = "http://cran.us.r-project.org")
```

```{r}
install.packages("ggplot2", version = "3.3.2", repos = "http://cran.us.r-project.org")
```

```{r}
install.packages("readr", version = "1.4.0", repos = "http://cran.us.r-project.org")
```

```{r}
install.packages("purrr", version = "0.3.4", repos = "http://cran.us.r-project.org")
```

```{r}
install.packages("purrr", version = "0.3.4", repos = "http://cran.us.r-project.org")
```

```{r}
install.packages("stringr", version = "1.4.0", repos = "http://cran.us.r-project.org")
```

```{r}
install.packages("forcats", version = "0.5.0", repos = "http://cran.us.r-project.org")
```

```{r}
install.packages("lme4", version = "1.1-23", repos = "http://cran.us.r-project.org")
```

```{r}
install.packages("feather", version = "0.3.5", repos = "http://cran.us.r-project.org")
```

```{r}
install.packages("viridis", version = "0.5.1", repos = "http://cran.us.r-project.org")
```
```{r}
install.packages("ggnewscale", version = "0.4.3", repos = "http://cran.us.r-project.org")
```
```{r}
install.packages("extrafont", version = "0.17", repos = "http://cran.us.r-project.org")
```
```{r}
install.packages("interactions", version = "1.1.3", repos = "http://cran.us.r-project.org")
```

```{r}
install.packages("RColorBrewer", version = "1.1-2", repos = "http://cran.us.r-project.org")
```

```{r}
packrat::snapshot()
```

